"""added updated datetime field

Revision ID: 15a7f500be51
Revises: cc412f397c31
Create Date: 2020-10-03 11:49:02.648426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a7f500be51'
down_revision = 'cc412f397c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'updated_at')
    # ### end Alembic commands ###
