"""added ItemBookmark model

Revision ID: 1812217d4a98
Revises: 757c26ad2474
Create Date: 2025-11-12 14:30:33.623468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1812217d4a98'
down_revision = '757c26ad2474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_bookmarks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_bookmarks')
    # ### end Alembic commands ###
