"""added subsubcategory field to the item model

Revision ID: 4ffa30b0de5e
Revises: 15a7f500be51
Create Date: 2020-10-03 11:59:12.160144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffa30b0de5e'
down_revision = '15a7f500be51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('subsubcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'sub_sub_categories', ['subsubcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'subsubcategory_id')
    # ### end Alembic commands ###
