"""added Bank and Category association table

Revision ID: 5586714dd90a
Revises: 2a63ac906b6e
Create Date: 2020-10-02 14:06:43.688280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5586714dd90a'
down_revision = '2a63ac906b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('bank_in', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_in'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_categories')
    # ### end Alembic commands ###
