"""added email field to user model

Revision ID: 70929ccffcff
Revises: 3d889cb36589
Create Date: 2020-11-27 05:03:30.342483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70929ccffcff'
down_revision = '3d889cb36589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
