"""added group note model

Revision ID: 71937d0a8218
Revises: c3a3ee2e1ed5
Create Date: 2024-01-07 14:29:51.757947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71937d0a8218'
down_revision = 'c3a3ee2e1ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_group_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['item_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'assoc_group_items', 'item_groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'assoc_group_items', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assoc_group_items', type_='foreignkey')
    op.drop_constraint(None, 'assoc_group_items', type_='foreignkey')
    op.drop_table('item_group_notes')
    # ### end Alembic commands ###
