"""added spec ID to the group model

Revision ID: 7574a100cef3
Revises: 59c272917622
Create Date: 2021-11-27 13:35:23.754522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7574a100cef3'
down_revision = '59c272917622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_groups', sa.Column('spec_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_groups', 'specifications', ['spec_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_groups', type_='foreignkey')
    op.drop_column('item_groups', 'spec_id')
    # ### end Alembic commands ###
