"""added Tag model

Revision ID: 757c26ad2474
Revises: 71937d0a8218
Create Date: 2024-03-09 11:35:14.385421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757c26ad2474'
down_revision = '71937d0a8218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assoc_tag_items',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assoc_tag_items')
    op.drop_table('tags')
    # ### end Alembic commands ###
