"""added sub-sub-category model

Revision ID: 80da16460956
Revises: a20171703e0e
Create Date: 2020-10-03 01:22:35.943222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80da16460956'
down_revision = 'a20171703e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_sub_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('ref_no', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['sub_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_sub_categories')
    # ### end Alembic commands ###
