"""added random set and item set test models

Revision ID: 89c330bc0466
Revises: f48a79498618
Create Date: 2023-01-14 05:37:29.130103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89c330bc0466'
down_revision = 'f48a79498618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_sets_testdrive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spec_id'], ['specifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('random_item_sets_testdrive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('choices_order', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['item_groups.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['random_sets_testdrive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    op.drop_table('random_item_sets_testdrive')
    op.drop_table('random_sets_test')
    # ### end Alembic commands ###
