"""removed answer ID field from item model

Revision ID: 98afa7d2a708
Revises: 1d52b9c397bf
Create Date: 2020-10-03 14:45:06.660576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98afa7d2a708'
down_revision = '1d52b9c397bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('items_answer_id_fkey', 'items', type_='foreignkey')
    op.drop_column('items', 'answer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('items_answer_id_fkey', 'items', 'choices', ['answer_id'], ['id'])
    # ### end Alembic commands ###
