"""added a model for a number of choice

Revision ID: a20171703e0e
Revises: 3f526dbb9a10
Create Date: 2020-10-02 15:07:43.099591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a20171703e0e'
down_revision = '3f526dbb9a10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('number_choice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('number_choice')
    # ### end Alembic commands ###
