"""added description to item group

Revision ID: b2bacffc4b18
Revises: 98749ee7b72c
Create Date: 2021-11-27 15:05:57.439597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bacffc4b18'
down_revision = '98749ee7b72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_groups', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_groups', 'desc')
    # ### end Alembic commands ###
