"""added filaname field to the figure model

Revision ID: cda53d5d1e84
Revises: f9f8b985616f
Create Date: 2020-11-14 15:39:01.740120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda53d5d1e84'
down_revision = 'f9f8b985616f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('figures', sa.Column('filename', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('figures', 'filename')
    # ### end Alembic commands ###
