"""added item orders field

Revision ID: cf019cabe493
Revises: 0d675e2fc1c4
Create Date: 2023-01-14 08:53:04.629730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf019cabe493'
down_revision = '0d675e2fc1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_sets_testdrive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_orders', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_sets_testdrive', schema=None) as batch_op:
        batch_op.drop_column('item_orders')

    # ### end Alembic commands ###
