"""added ref number and changed the type of the name field to text

Revision ID: d28e00a8a7e9
Revises: 5586714dd90a
Create Date: 2020-10-02 14:09:39.409257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28e00a8a7e9'
down_revision = '5586714dd90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_categories', sa.Column('ref_no', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_categories', 'ref_no')
    # ### end Alembic commands ###
