"""added num sample item field

Revision ID: db1e85f0d00e
Revises: b2bacffc4b18
Create Date: 2022-02-12 13:44:47.432313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1e85f0d00e'
down_revision = 'b2bacffc4b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_groups', sa.Column('num_sample_items', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_groups', 'num_sample_items')
    # ### end Alembic commands ###
