"""added submitted datetime field

Revision ID: effc31584857
Revises: d9ea4966f403
Create Date: 2023-01-14 11:18:36.672919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effc31584857'
down_revision = 'd9ea4966f403'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_sets_testdrive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('random_sets_testdrive', schema=None) as batch_op:
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###
